### ISSUE TITLE
Support for other shells

### ISSUE THREAD

**Issue by TheHippo** [pote/gvp#17]
Any plans to support other shells, like [fish shell](http://fishshell.com/)?

**Comment by siddharthist** [comment]
^ Broken link. Check out http://fishshell.com/docs/current/faq.html#faq-envvar

**Comment by siddharthist** [comment]
Theoretically, if fish supported any of bash syntax, this could probably be done by reading the $SHELL environment variable, and setting up a conditional. Unfortunately, fish has [completely different scripting language](https://github.com/fish-shell/fish-shell/issues/522), and this is not possible without maintaining two copies of gvp, which seems like a separate project rather than something to be done here.

**Comment by siddharthist** [comment]
@pote I feel like this is probably ready to close, gvp couldn't support fish without a complete rewrite. Feedback?

**Comment by pote** [comment]
@siddharthist I agree. it's a shame we can't support fish, but I think the amount of work it'd require is prohibitive.
